name: Java CI

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build with Gradle
        run: ./gradlew test
        env:
          KEY_STORE_PASS: ${{ secrets.KEY_STORE_PASS }}
          KEY_STORE_ALIAS: ${{ secrets.KEY_STORE_ALIAS }}
          KEY_STORE_KEY_PASS: ${{ secrets.KEY_STORE_KEY_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH: ${{ secrets.MODRINTH }}
          CURSE: ${{ secrets.CURSE }}